IMAGE_PATH="./images/"
BASE_IMAGE="IMG_0573.JPG"

ALIGNMENT_DETECTOR="SIFT"  #SIFT or SURF
ALIGNMENT_FEATURE_NUM=2000

HIST_MATCHING=True

LAP_KERNEL_SIZE=3

SLIDE_WINDOW_SIZE=100
SLIDE_WINDOW_STEP=10

DENOISE=False